-- ATS Registry: dynamic company-board discovery for Greenhouse, Lever, Ashby.
-- The job fetcher reads this table at runtime instead of a hard-coded list and
-- auto-discovers new boards by probing company-name slugs.

CREATE TABLE IF NOT EXISTS public.ats_registry (
    id          uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
    slug        text        NOT NULL,
    ats         text        NOT NULL CHECK (ats IN ('greenhouse', 'lever', 'ashby')),
    display_name text       NOT NULL DEFAULT '',
    found       boolean     NOT NULL DEFAULT false,
    enabled     boolean     NOT NULL DEFAULT true,
    last_probed_at timestamptz DEFAULT now(),
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE(slug, ats)
);

CREATE INDEX IF NOT EXISTS idx_ats_registry_active
    ON public.ats_registry (ats) WHERE found = true AND enabled = true;

-- Seed with verified companies (April 2026 scan: 105 Greenhouse, 6 Lever, 49 Ashby)
INSERT INTO public.ats_registry (slug, ats, display_name, found) VALUES
-- ── Greenhouse ──
('adyen','greenhouse','Adyen',true),
('affirm','greenhouse','Affirm',true),
('airbnb','greenhouse','Airbnb',true),
('airtable','greenhouse','Airtable',true),
('alma','greenhouse','Alma',true),
('amplitude','greenhouse','Amplitude',true),
('anthropic','greenhouse','Anthropic',true),
('apollo','greenhouse','Apollo',true),
('archer','greenhouse','Archer',true),
('asana','greenhouse','Asana',true),
('astranis','greenhouse','Astranis',true),
('bandwidth','greenhouse','Bandwidth',true),
('betterment','greenhouse','Betterment',true),
('block','greenhouse','Block',true),
('brex','greenhouse','Brex',true),
('calm','greenhouse','Calm',true),
('carta','greenhouse','Carta',true),
('cerebral','greenhouse','Cerebral',true),
('chime','greenhouse','Chime',true),
('clickhouse','greenhouse','ClickHouse',true),
('cloudflare','greenhouse','Cloudflare',true),
('coinbase','greenhouse','Coinbase',true),
('contentful','greenhouse','Contentful',true),
('coupang','greenhouse','Coupang',true),
('coursera','greenhouse','Coursera',true),
('cybereason','greenhouse','Cybereason',true),
('databricks','greenhouse','Databricks',true),
('datadog','greenhouse','Datadog',true),
('discord','greenhouse','Discord',true),
('dotmatics','greenhouse','Dotmatics',true),
('dremio','greenhouse','Dremio',true),
('dropbox','greenhouse','Dropbox',true),
('duolingo','greenhouse','Duolingo',true),
('earnin','greenhouse','Earnin',true),
('elastic','greenhouse','Elastic',true),
('fastly','greenhouse','Fastly',true),
('figma','greenhouse','Figma',true),
('fivetran','greenhouse','Fivetran',true),
('flexport','greenhouse','Flexport',true),
('forter','greenhouse','Forter',true),
('fourkites','greenhouse','FourKites',true),
('ghost','greenhouse','Ghost',true),
('gitlab','greenhouse','GitLab',true),
('greenhouse','greenhouse','Greenhouse',true),
('gusto','greenhouse','Gusto',true),
('hackerrank','greenhouse','HackerRank',true),
('honeycomb','greenhouse','Honeycomb',true),
('instacart','greenhouse','Instacart',true),
('intercom','greenhouse','Intercom',true),
('justworks','greenhouse','Justworks',true),
('karat','greenhouse','Karat',true),
('labelbox','greenhouse','Labelbox',true),
('lattice','greenhouse','Lattice',true),
('launchdarkly','greenhouse','LaunchDarkly',true),
('lithic','greenhouse','Lithic',true),
('lyft','greenhouse','Lyft',true),
('marqeta','greenhouse','Marqeta',true),
('mixpanel','greenhouse','Mixpanel',true),
('mongodb','greenhouse','MongoDB',true),
('motional','greenhouse','Motional',true),
('netlify','greenhouse','Netlify',true),
('nextdoor','greenhouse','Nextdoor',true),
('nuro','greenhouse','Nuro',true),
('okta','greenhouse','Okta',true),
('oscar','greenhouse','Oscar Health',true),
('oura','greenhouse','Oura',true),
('pagerduty','greenhouse','PagerDuty',true),
('payoneer','greenhouse','Payoneer',true),
('peloton','greenhouse','Peloton',true),
('pinterest','greenhouse','Pinterest',true),
('planetscale','greenhouse','PlanetScale',true),
('plume','greenhouse','Plume',true),
('project44','greenhouse','project44',true),
('reddit','greenhouse','Reddit',true),
('relativity','greenhouse','Relativity',true),
('remote','greenhouse','Remote',true),
('riskified','greenhouse','Riskified',true),
('robinhood','greenhouse','Robinhood',true),
('roblox','greenhouse','Roblox',true),
('root','greenhouse','Root Insurance',true),
('salesloft','greenhouse','SalesLoft',true),
('samsara','greenhouse','Samsara',true),
('scopely','greenhouse','Scopely',true),
('smartsheet','greenhouse','Smartsheet',true),
('sofi','greenhouse','SoFi',true),
('spacex','greenhouse','SpaceX',true),
('squarespace','greenhouse','Squarespace',true),
('starburst','greenhouse','Starburst',true),
('stripe','greenhouse','Stripe',true),
('tailscale','greenhouse','Tailscale',true),
('tanium','greenhouse','Tanium',true),
('thumbtack','greenhouse','Thumbtack',true),
('toast','greenhouse','Toast',true),
('turing','greenhouse','Turing',true),
('twilio','greenhouse','Twilio',true),
('twitch','greenhouse','Twitch',true),
('udemy','greenhouse','Udemy',true),
('upwork','greenhouse','Upwork',true),
('vercel','greenhouse','Vercel',true),
('veracyte','greenhouse','Veracyte',true),
('verkada','greenhouse','Verkada',true),
('vonage','greenhouse','Vonage',true),
('waymo','greenhouse','Waymo',true),
('webflow','greenhouse','Webflow',true),
('zscaler','greenhouse','Zscaler',true),
-- ── Lever ──
('kabam','lever','Kabam',true),
('neon','lever','Neon',true),
('palantir','lever','Palantir',true),
('ro','lever','Ro',true),
('toptal','lever','Toptal',true),
('veeva','lever','Veeva',true),
-- ── Ashby ──
('acorns','ashby','Acorns',true),
('airbyte','ashby','Airbyte',true),
('andela','ashby','Andela',true),
('anyscale','ashby','Anyscale',true),
('ashby','ashby','Ashby',true),
('benchling','ashby','Benchling',true),
('capsule','ashby','Capsule',true),
('clickup','ashby','ClickUp',true),
('cohere','ashby','Cohere',true),
('confluent','ashby','Confluent',true),
('cursor','ashby','Cursor',true),
('dave','ashby','Dave',true),
('deel','ashby','Deel',true),
('deepgram','ashby','Deepgram',true),
('forge','ashby','Forge',true),
('fullstory','ashby','FullStory',true),
('gamma','ashby','Gamma',true),
('helpscout','ashby','Help Scout',true),
('hims-and-hers','ashby','Hims & Hers',true),
('lemonade','ashby','Lemonade',true),
('linear','ashby','Linear',true),
('livekit','ashby','LiveKit',true),
('mollie','ashby','Mollie',true),
('nerdwallet','ashby','NerdWallet',true),
('notion','ashby','Notion',true),
('openai','ashby','OpenAI',true),
('orca','ashby','Orca Security',true),
('oyster','ashby','Oyster',true),
('perplexity','ashby','Perplexity',true),
('plaid','ashby','Plaid',true),
('prefect','ashby','Prefect',true),
('railway','ashby','Railway',true),
('ramp','ashby','Ramp',true),
('redis','ashby','Redis',true),
('render','ashby','Render',true),
('sanity','ashby','Sanity',true),
('saronic','ashby','Saronic',true),
('sentry','ashby','Sentry',true),
('sift','ashby','Sift',true),
('skydio','ashby','Skydio',true),
('snowflake','ashby','Snowflake',true),
('supercell','ashby','Supercell',true),
('supabase','ashby','Supabase',true),
('talkiatry','ashby','Talkiatry',true),
('unit','ashby','Unit',true),
('vanta','ashby','Vanta',true),
('wealthsimple','ashby','Wealthsimple',true),
('whoop','ashby','WHOOP',true),
('writer','ashby','Writer',true)
ON CONFLICT (slug, ats) DO NOTHING;
